# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: center
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - torso_to_neck
    - neck_to_head
    - torso_to_shoulder
    - shoulder_to_arm_l1
    - arm_l1_to_forearm
    - forearm_to_wrist_shaft
    - wrist_shaft_to_wrist
    - wrist_to_gripper
    - gripper_to_finger_l
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - torso_to_shoulder
      - shoulder_to_arm_l1
      - arm_l1_to_forearm
      - forearm_to_wrist_shaft
      - wrist_shaft_to_wrist
      - wrist_to_gripper
  - name: hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      []
  - name: head_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - torso_to_neck
      - neck_to_head
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - torso_to_shoulder
    - shoulder_to_arm_l1
    - arm_l1_to_forearm
    - forearm_to_wrist_shaft
    - wrist_shaft_to_wrist
    - wrist_to_gripper
  gains:
    torso_to_shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_to_arm_l1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_l1_to_forearm:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    forearm_to_wrist_shaft:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_shaft_to_wrist:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_to_gripper:
      p: 100
      d: 1
      i: 1
      i_clamp: 1